language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
      env:
        - R_CODECOV=true
    - os: linux
      r: devel
    - os: linux
      r: oldrel
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    packages:
    - libglpk-dev

r_github_packages:
  - hadley/testthat
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::coveralls()'
